development:
  adapter: postgresql
  encoding: unicode
  database: crm_development
  pool: 5
  username: 
  password:
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: crm_test
  pool: 5
  username: 
  password:
  timeout: 5000


