# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b02bd838052cbc70565abc2629429a928a9268d5acaea92d8045e0585d1bf2bee05f3769698a2a6d15f0acd9ef0ab7b68e0566e6cf1786f508b416c2e4b165b

test:
  secret_key_base: fcdfda93b9f8d88e1ffd047e4ea46b2cf4ee1ae31709a3149affdbc4929b21aea207a5aad3a7e3ee8be0bfe9be0a31bdd8f1b06a82f4dc708fb777a99080514e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
